version: 2

jobs:

  # python3:
  build:
    working_directory: ~/tablify
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip pandoc
      - run: pip3 install -U pytest pytest-cov pylint bandit
      - checkout
      - run: pip3 install .
      # lint, bandit
      - run: pylint setup.py tablify/ test/*.py
      - run: bandit -r .
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov tablify
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
