version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install --user black flake8
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: pip3 install --user pytest pytest-cov
      - checkout
      - run: pip3 install --user .
      # The tests
      - run:
          command: pytest --cov tablign
          working_directory: test/
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
